/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jt28_a6735_android_opencv_ndk_OpenCVHelper */

#ifndef _Included_com_jt28_a6735_android_opencv_ndk_OpenCVHelper
#define _Included_com_jt28_a6735_android_opencv_ndk_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jt28_a6735_android_opencv_ndk_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jt28_a6735_android_1opencv_1ndk_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_jt28_a6735_android_opencv_ndk_OpenCVHelper
 * Method:    roi_add
 * Signature: ([I[IIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jt28_a6735_android_1opencv_1ndk_OpenCVHelper_roi_1add
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
